"""
© Ocado Group
Created on 23/01/2024 at 11:05:41(+00:00).
"""

from codeforlife.user.models import School
from codeforlife.user.serializers import SchoolSerializer as _SchoolSerializer
from rest_framework import serializers


# pylint: disable-next=missing-class-docstring,too-many-ancestors
class SchoolSerializer(_SchoolSerializer):
    country = serializers.ChoiceField(  # type: ignore[assignment]
        choices=[
            "AF",
            "AX",
            "AL",
            "DZ",
            "AS",
            "AD",
            "AO",
            "AI",
            "AQ",
            "AG",
            "AR",
            "AM",
            "AW",
            "AU",
            "AT",
            "AZ",
            "BS",
            "BH",
            "BD",
            "BB",
            "BY",
            "BE",
            "BZ",
            "BJ",
            "BM",
            "BT",
            "BO",
            "BQ",
            "BA",
            "BW",
            "BV",
            "BR",
            "IO",
            "BN",
            "BG",
            "BF",
            "BI",
            "KH",
            "CM",
            "CA",
            "CV",
            "KY",
            "CF",
            "TD",
            "CL",
            "CN",
            "CX",
            "CC",
            "CO",
            "KM",
            "CG",
            "CD",
            "CK",
            "CR",
            "CI",
            "HR",
            "CU",
            "CW",
            "CY",
            "CZ",
            "DK",
            "DJ",
            "DM",
            "DO",
            "EC",
            "EG",
            "SV",
            "GQ",
            "ER",
            "EE",
            "ET",
            "FK",
            "FO",
            "FJ",
            "FI",
            "FR",
            "GF",
            "PF",
            "TF",
            "GA",
            "GM",
            "GE",
            "DE",
            "GH",
            "GI",
            "GR",
            "GL",
            "GD",
            "GP",
            "GU",
            "GT",
            "GG",
            "GN",
            "GW",
            "GY",
            "HT",
            "HM",
            "VA",
            "HN",
            "HK",
            "HU",
            "IS",
            "IN",
            "ID",
            "IR",
            "IQ",
            "IE",
            "IM",
            "IL",
            "IT",
            "JM",
            "JP",
            "JE",
            "JO",
            "KZ",
            "KE",
            "KI",
            "KP",
            "KR",
            "KW",
            "KG",
            "LA",
            "LV",
            "LB",
            "LS",
            "LR",
            "LY",
            "LI",
            "LT",
            "LU",
            "MO",
            "MK",
            "MG",
            "MW",
            "MY",
            "MV",
            "ML",
            "MT",
            "MH",
            "MQ",
            "MR",
            "MU",
            "YT",
            "MX",
            "FM",
            "MD",
            "MC",
            "MN",
            "ME",
            "MS",
            "MA",
            "MZ",
            "MM",
            "NA",
            "NR",
            "NP",
            "NL",
            "NC",
            "NZ",
            "NI",
            "NE",
            "NG",
            "NU",
            "NF",
            "MP",
            "NO",
            "OM",
            "PK",
            "PW",
            "PS",
            "PA",
            "PG",
            "PY",
            "PE",
            "PH",
            "PN",
            "PL",
            "PT",
            "PR",
            "QA",
            "RE",
            "RO",
            "RU",
            "RW",
            "BL",
            "SH",
            "KN",
            "LC",
            "MF",
            "PM",
            "VC",
            "WS",
            "SM",
            "ST",
            "SA",
            "SN",
            "RS",
            "SC",
            "SL",
            "SG",
            "SX",
            "SK",
            "SI",
            "SB",
            "SO",
            "ZA",
            "GS",
            "SS",
            "ES",
            "LK",
            "SD",
            "SR",
            "SJ",
            "SZ",
            "SE",
            "CH",
            "SY",
            "TW",
            "TJ",
            "TZ",
            "TH",
            "TL",
            "TG",
            "TK",
            "TO",
            "TT",
            "TN",
            "TR",
            "TM",
            "TC",
            "TV",
            "UG",
            "UA",
            "AE",
            "GB",
            "US",
            "UM",
            "UY",
            "UZ",
            "VU",
            "VE",
            "VN",
            "VG",
            "VI",
            "WF",
            "EH",
            "YE",
            "ZM",
            "ZW",
        ],
    )

    uk_county = serializers.ChoiceField(  # type: ignore[assignment]
        source="county",
        default="",
        choices=[
            "Aberdeen City",
            "Aberdeenshire",
            "Angus",
            "Argyll and Bute",
            "Bedfordshire",
            "Belfast",
            "Belfast Greater",
            "Berkshire",
            "Blaenau Gwent",
            "Bridgend",
            "Buckinghamshire",
            "Caerphilly",
            "Cambridgeshire",
            "Cardiff",
            "Carmarthenshire",
            "Ceredigion",
            "Channel Islands",
            "Cheshire",
            "City of Edinburgh",
            "Clackmannanshire",
            "Conwy",
            "Cornwall",
            "County Antrim",
            "County Armagh",
            "County Down",
            "County Fermanagh",
            "County Londonderry",
            "County Tyrone",
            "County of Bristol",
            "Cumbria",
            "Denbighshire",
            "Derbyshire",
            "Devon",
            "Dorset",
            "Dumfries and Galloway",
            "Dunbartonshire",
            "Dundee City",
            "Durham",
            "East Ayrshire",
            "East Dunbartonshire",
            "East Lothian",
            "East Renfrewshire",
            "East Riding of Yorkshire",
            "East Sussex",
            "Essex",
            "Falkirk",
            "Fife",
            "Flintshire",
            "Glasgow City",
            "Gloucestershire",
            "Greater London",
            "Greater Manchester",
            "Guernsey Channel Islands",
            "Gwynedd",
            "Hampshire",
            "Hereford and Worcester",
            "Herefordshire",
            "Hertfordshire",
            "Highland",
            "Inverclyde",
            "Inverness",
            "Isle of Anglesey",
            "Isle of Barra",
            "Isle of Man",
            "Isle of Wight",
            "Jersey Channel Islands",
            "Kent",
            "Lancashire",
            "Leicestershire",
            "Lincolnshire",
            "Merseyside",
            "Merthyr Tydfil",
            "Midlothian",
            "Monmouthshire",
            "Moray",
            "Neath Port Talbot",
            "Newport",
            "Norfolk",
            "North Ayrshire",
            "North Lanarkshire",
            "North Yorkshire",
            "Northamptonshire",
            "Northumberland",
            "Nottinghamshire",
            "Orkney",
            "Orkney Islands",
            "Oxfordshire",
            "Pembrokeshire",
            "Perth and Kinross",
            "Powys",
            "Renfrewshire",
            "Rhondda Cynon Taff",
            "Rutland",
            "Scottish Borders",
            "Shetland Islands",
            "Shropshire",
            "Somerset",
            "South Ayrshire",
            "South Lanarkshire",
            "South Yorkshire",
            "Staffordshire",
            "Stirling",
            "Suffolk",
            "Surrey",
            "Swansea",
            "Torfaen",
            "Tyne and Wear",
            "Vale of Glamorgan",
            "Warwickshire",
            "West Dunbart",
            "West Lothian",
            "West Midlands",
            "West Sussex",
            "West Yorkshire",
            "Western Isles",
            "Wiltshire",
            "Worcestershire",
            "Wrexham",
        ],
    )

    class Meta(_SchoolSerializer.Meta):
        extra_kwargs = {
            **_SchoolSerializer.Meta.extra_kwargs,
            "name": {"read_only": False},
        }

    # TODO: set unique=True for model name field in new models.
    # pylint: disable-next=missing-function-docstring
    def validate_name(self, value: str):
        if School.objects.filter(name=value).exists():
            raise serializers.ValidationError(
                "Name already taken.",
                code="name_not_unique",
            )

        return value

    def validate(self, attrs):
        if "uk_county" in attrs:
            country = attrs.get(
                "country",
                self.instance.country if self.view.action != "create" else None,
            )
            if country != "GB":
                raise serializers.ValidationError(
                    "Cannot set the UK county when country is not set to GB.",
                    code="country_ne_gb",
                )

        return attrs
