import {
  Button,
  Stack
} from '@mui/material';
import React from 'react';
import { useNavigate } from 'react-router-dom';
import * as Yup from 'yup';

import {
  SubmitButton,
  TextField
} from 'codeforlife/lib/esm/components/form';

import { useLoginMutation } from '../../../app/api';
import { paths } from '../../../app/router';
import LoginForm from '../LoginForm';

const Otp: React.FC = () => {
  const navigate = useNavigate();
  const { data } = useLoginMutation()[1];

  return (
    <LoginForm
      themedBoxProps={{ userType: 'teacher' }}
      header='Welcome'
      subheader='Please enter the token generated by your token generator.'
      initialValues={{ otp: '' }}
      authFactors={{
        includes: 'otp',
        pathToFirstStep: paths.login.teacher._
      }}
      onSubmit={() => ({
        navigateTo: paths.teacher.dashboard.school._,
        isEnd: true
      })}
    >
      <TextField
        name='otp'
        helperText='Enter your code from your app'
        validate={Yup.string().matches(/^[0-9]{6}$/, 'Invalid token')}
        required
      />
      {data?.otpBypassTokenExists &&
        <Button
          className='body'
          onClick={() => { navigate(paths.login.teacher.otp.bypassToken._); }}
        >
          Use a backup token
        </Button>
      }
      <Stack direction='row' spacing={2} justifyContent='space-between'>
        <Button
          onClick={() => { navigate(paths.login.teacher._); }}
          variant='outlined'
        >
          Cancel
        </Button>
        <SubmitButton />
      </Stack>
    </LoginForm>
  );
};

export default Otp;
