import React from 'react';

import { paths } from '../../app/router';
import BasePage from '../../pages/BasePage';
import PageSection from '../../components/PageSection';
import BaseForm from './BaseForm';
import { SubmitButton, TextField } from 'codeforlife/lib/esm/components/form';
import * as Yup from 'yup';
import { Button, Stack } from '@mui/material';

const Login2fa: React.FC = () => {
  return (
    <BasePage>
      <PageSection maxWidth='md'>
        <BaseForm
          themedBoxProps={{ userType: 'teacher' }}
          header='Welcome'
          subheader='Please enter the token generated by your token generator.'
          initialValues={{}}
          onSubmit={(values, { setSubmitting }) => {
            // TODO: Connect this to the backend
            console.log(values);
            setSubmitting(false);
          }}
        >
          <TextField
            name="token"
            helperText="Enter your code from your app"
            validate={Yup
              .string()
              .required()
              .matches(/^[0-9]{6}$/, 'Invalid token')}
            required
          />
          <Stack spacing={2}>
            <Button variant="contained" color="tertiary" href={paths.login2faBackup}>
              Use a backup token
            </Button>
            <Stack direction="row" spacing={2} justifyContent="space-between">
              <Button variant="contained" color="tertiary" href={paths.login.teacher}>
                Cancel
              </Button>
              <SubmitButton
                // TODO: Remove href and replace with submit functionality
                href={paths.teacherSchool}>
                Submit
              </SubmitButton>
            </Stack>
          </Stack>
        </BaseForm>
      </PageSection>
    </BasePage>
  );
};

export default Login2fa;
