import React from 'react';
import BasePage from '../../../BasePage';
import DashboardBanner from '../../DashboardBanner';
import DashboardHeader from '../../DashboardHeader';
import { Button, Stack, Typography } from '@mui/material';
import PageSection from '../../../../components/PageSection';
import { Form, SubmitButton, TextField } from 'codeforlife/lib/esm/components/form';
import { paths } from '../../../../app/router';
import { Image } from 'codeforlife/lib/esm/components';
import cflLogo from '../../../../images/cfl_logo.png';
import * as Yup from 'yup';
const BackupTokens: React.FC = (): JSX.Element => {
  return (
    <BasePage>
      <DashboardBanner />
      <DashboardHeader page="Your account" />
      <PageSection>
        <Typography align="center" variant="h4">
          Two-factor authentication
        </Typography>
        <Typography>
          Two-factor authentication is not currently set up on your account. Enable two-factor authentication (2FA) for
          enhanced account security.
        </Typography>
        <Typography>
          To start using a token generator, please use your smartphone to scan the QR code below. For example, use
          Google Authenticator.
        </Typography>
        <Image
          alt='QR code'
          // TODO: Replace image with generated QR code from backend library
          src={cflLogo}
          maxWidth='230px'
        />
        <Form
          initialValues={{}}
          onSubmit={(values, { setSubmitting }) => {
          // TODO: to call backend
          setSubmitting(false);
        }}>
          <TextField
            required
            name="token"
            helperText="Enter token generated by app"
            validate={Yup
              .string()
              .required()
              .matches(/^[0-9]{6}$/, 'Invalid token')
            }
            sx={{ width: 1 / 5 }}
          />
          <Stack direction="row" spacing={2} justifyContent="flex-end">
            <Button variant="contained" color="tertiary" href={paths.teacherSchool}>
              Cancel
            </Button>
            <SubmitButton
              // TODO: Remove href and replace with submit functionality
              href={paths.setup2faComplete}>
              Next
            </SubmitButton>
          </Stack>
        </Form>
      </PageSection>
    </BasePage>
  );
};

export default BackupTokens;
